### ISSUE TITLE
Video player doesn't load initially, does on page refresh.

### ISSUE THREAD

**Issue by AnthonyBRoberts** [bodrovis/SitePoint-YtVideos#1]
http://anthonybroberts.com/videos

So I implemented this, which is extremely helpful, so thank you. 

But on my site, the player doesn't load when I go to the page, but will load if I hit refresh.  

This is the github repo: https://github.com/AnthonyBRoberts/rails_tut

I've tried this on IE, Chrome, and FF, so I think the issue is repeatable.

**Comment by bodrovis** [comment]
@AnthonyBRoberts Sorry for the late response, I was away for a couple of days. I will take a look at this soon!

**Comment by bodrovis** [comment]
@AnthonyBRoberts Okay, one of the possible causes is the `turbolinks` gem (https://github.com/AnthonyBRoberts/rails_tut/blob/master/app/assets/javascripts/application.js#L16). As long as it uses its own events (https://github.com/rails/turbolinks/#events), `$(document).ready(function() {});` does not work anymore and it might break functionality of the YT player. You can either switch off turbolinks and see if this helps or use a gem called `jquery-turbolinks` (https://github.com/kossnocorp/jquery.turbolinks) to bring default jQuery events back. Note that other jQuery plugins may also break because of turbolinks if you do not use `jquery-turbolinks`.

Please let me know if that helped.
